@host= http://localhost:5034
POST {{host}}/auth/register
content-type: application/json

{
  "username": "john_dou",
  "email": "john@example.com",
  "password": "securePassword123",
  "firstname": "john",
  "lastname": "dou"
}