@host= http://localhost:5034
@hostId=b13562c8-069a-4e55-897d-a2679c0fe8df
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huQGV4YW1wbGUuY29tIiwibmFtZSI6ImpvaG4iLCJmYW1pbHlfbmFtZSI6ImRvdSIsImp0aSI6IjJiNDhmZjZjLTJiMTAtNGJiOC04ZThmLWVhNDZiOTZjZTU4YiIsImV4cCI6MTcyNTk3NjExOCwiaXNzIjoiU1NTIiwiYXVkIjoiU1NTIn0.g3df69QjCnWSSHeqiBw_fv6B-4JHikq5WTPOEweCoMU
POST {{host}}/hosts/{{hostId}}/menus
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Delicious Bites Menu",
  "description": "A delightful selection of appetizers, main courses, desserts, and beverages.",
  "sections": [ 
    {
      "name": "Appetizers",
      "description": "Start your meal with our delicious appetizers.",
      "items": [
        {
          "name": "Garlic Bread",
          "description": "Toasted bread with garlic butter and herbs",
          "price": 4.99
        }, 
        {
          "name": "Bruschetta",
          "description": "Grilled bread topped with tomatoes, basil, and olive oil",
          "price": 5.99
        }
      ]
    },
    {
      "name": "Main Courses",
      "description": "Satisfy your hunger with our hearty main courses.",
      "items": [
        {
          "name": "Spaghetti Carbonara",
          "description": "Pasta with eggs, cheese, pancetta, and black pepper",
          "price": 12.99
        },
        {
          "name": "Chicken Alfredo",
          "description": "Grilled chicken with creamy Alfredo sauce over fettuccine",
          "price": 14.99
        }
      ]
    }
   ]
}