@host= http://localhost:5034
POST {{host}}/auth/register


### Request

#### Headers
Content-Type: application/json

#### Body
{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "securePassword123"
}